workflows:
  my-workflow:
    name: My new workflow 
    labels:
      - QA
      - Shabana
    instance_type: mac_mini_m1
    max_build_duration: 100
    environment:
      groups:
        - keystore_credentials
        - app_store_credentials
      vars:
        PUBLIC_ENV_VAR: "value here"
      flutter: beta
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - ...
    artifacts:
      - build/**/outputs/bundle/**/*.aab
    publishing:
      email:
        recipients:
          - shaiknasreen0901@gmail.com
      scripts:
        - echo 'Post-publish script'